#%RAML 1.0
title: wco-eapi-ecommerce
protocols:
  - HTTP
  - HTTPS

/customer/{customerid}:
  uriParameters:
    customerid:
      type: number
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
          "customerDetails": [
        {
        "locationCode__c": "gnt",
        "customerid__c": "12",
        "Id": null,
        "type": "eproducts__c",
        "Name": "green light"
          }
        ]
     }

/user:
  get:
    queryParameters:
      page:
        type: number
        required: true
    responses:
      200:
        body:
          application/json:
            example: !include examples/user-details-by-page-response-example.json

/accountValidate:
  post:
    body:
      application/json:
        example:
               {
                "accountID": 2323,
                "target1": "rest api",
                "target2": "soql"
               }
    responses:
      200:
        body:
          application/json:
            {
              
            }




/emailSignup:
  post:
    body:
      application/json:
        type: !include /datatypes/emailsignup-request-dataType.raml
        example: !include examples/emailsignup-request-file.json
         
    responses:
      200:
        body:
          application/json:
            type: !include /datatypes/emailsignup-response-dataType.raml
            example: !include examples/emailsignup-response-file.json

                 


           